In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/social-network-ads/Social_Network_Ads.csv


In [2]:
df=pd.read_csv('/kaggle/input/social-network-ads/Social_Network_Ads.csv')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.shape

(400, 5)

In [5]:
df.drop(columns=['User ID'], inplace=True)

In [6]:
df.shape

(400, 4)

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [8]:
df['Gender']= encoder.fit_transform(df['Gender'])

In [9]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [10]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [11]:
X

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000],
       ...,
       [    0,    50, 20000],
       [    1,    36, 33000],
       [    0,    49, 36000]])

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [14]:
X=scaler.fit_transform(X)

In [15]:
X

array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]])

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 3)
(80, 3)
(320,)
(80,)


In [18]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

**Batch Gradient Descent**

In [19]:
model=Sequential()

In [20]:
model.add(Dense(1,activation='sigmoid',input_dim=X_train.shape[1]))

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [23]:
import time

In [24]:
start = time.time()
model.fit(X_train,y_train,batch_size=320,epochs=100,verbose=1)
print(time.time() - start)

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 0.5814 - accuracy: 0.6938
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 0.5809 - accuracy: 0.6938
Epoch 3/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5804 - accuracy: 0.6938
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5799 - accuracy: 0.6938
Epoch 5/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5794 - accuracy: 0.6938
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5789 - accuracy: 0.6938
Epoch 7/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5784 - accuracy: 0.6938
Epoch 8/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5779 - accuracy: 0.6938
Epoch 9/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5774 - accuracy: 0.6938
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5769 - accuracy: 0.6938
Epoch 11/100
1/1 [===========

In [25]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 1ms/step - loss: 0.3971 - accuracy: 0.8500


[0.3971031904220581, 0.8500000238418579]

In [26]:
model.get_weights()

[array([[0.60141546],
        [1.2957389 ],
        [0.02419322]], dtype=float32),
 array([-0.09768548], dtype=float32)]

**Stochastic Gradient Descent**

In [27]:
model=Sequential()

In [28]:
model.add(Dense(1,activation='sigmoid',input_dim=X_train.shape[1]))

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [31]:
start = time.time()
model.fit(X_train,y_train,batch_size=1,epochs=100,verbose=1)
print(time.time() - start)

Epoch 1/100
320/320 [==============================] - 0s 805us/step - loss: 0.7232 - accuracy: 0.5656
Epoch 2/100
320/320 [==============================] - 0s 818us/step - loss: 0.6629 - accuracy: 0.6062
Epoch 3/100
320/320 [==============================] - 0s 830us/step - loss: 0.6141 - accuracy: 0.6375
Epoch 4/100
320/320 [==============================] - 0s 833us/step - loss: 0.5739 - accuracy: 0.6594
Epoch 5/100
320/320 [==============================] - 0s 833us/step - loss: 0.5409 - accuracy: 0.7156
Epoch 6/100
320/320 [==============================] - 0s 856us/step - loss: 0.5143 - accuracy: 0.7563
Epoch 7/100
320/320 [==============================] - 0s 858us/step - loss: 0.4928 - accuracy: 0.7750
Epoch 8/100
320/320 [==============================] - 0s 872us/step - loss: 0.4751 - accuracy: 0.8000
Epoch 9/100
320/320 [==============================] - 0s 876us/step - loss: 0.4609 - accuracy: 0.7969
Epoch 10/100
320/320 [==============================] - 0s 858us/step - l

In [32]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 1ms/step - loss: 0.2022 - accuracy: 0.9250


[0.20223291218280792, 0.925000011920929]

In [33]:
model.get_weights()

[array([[0.09182088],
        [2.1806042 ],
        [1.1379148 ]], dtype=float32),
 array([-1.0256135], dtype=float32)]

**Mini Batch Gradient Descent**

In [34]:
model=Sequential()

In [35]:
model.add(Dense(1,activation='sigmoid',input_dim=X_train.shape[1]))

In [36]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [38]:
start = time.time()
model.fit(X_train,y_train,batch_size=10,epochs=100,verbose=1)
print(time.time() - start)

Epoch 1/100
32/32 [==============================] - 0s 851us/step - loss: 0.7844 - accuracy: 0.4281
Epoch 2/100
32/32 [==============================] - 0s 817us/step - loss: 0.7694 - accuracy: 0.4594
Epoch 3/100
32/32 [==============================] - 0s 860us/step - loss: 0.7554 - accuracy: 0.4812
Epoch 4/100
32/32 [==============================] - 0s 830us/step - loss: 0.7419 - accuracy: 0.4969
Epoch 5/100
32/32 [==============================] - 0s 839us/step - loss: 0.7290 - accuracy: 0.5250
Epoch 6/100
32/32 [==============================] - 0s 824us/step - loss: 0.7165 - accuracy: 0.5562
Epoch 7/100
32/32 [==============================] - 0s 842us/step - loss: 0.7047 - accuracy: 0.5906
Epoch 8/100
32/32 [==============================] - 0s 854us/step - loss: 0.6932 - accuracy: 0.6062
Epoch 9/100
32/32 [==============================] - 0s 825us/step - loss: 0.6823 - accuracy: 0.6313
Epoch 10/100
32/32 [==============================] - 0s 811us/step - loss: 0.6719 - accura

In [39]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 1ms/step - loss: 0.2669 - accuracy: 0.9125


[0.266890287399292, 0.9125000238418579]

In [40]:
model.get_weights()

[array([[-0.00727106],
        [ 1.3712425 ],
        [ 0.8245468 ]], dtype=float32),
 array([-0.72135526], dtype=float32)]

**BGD is not performing well in the test model. SGD is slightly performing better than Mini-Batch.**

**On the other hand, the time taken by Mini-batch is very less than SGD. And BGD is taking a lot of time.**

*So, in both ways BGD is not a good choice in this case.*